name: Pull Request Workflow
on:
 pull_request:
  types:
    - opened

jobs:
  ci-job:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '8'  
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn  package
