name: GAME_SERVER-AVALON
on:
 push:
  branches:
   - main

#具體要執行步驟
jobs:
  job1:
   #什麼OS下運行
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '8'  # 可以改版本
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn  package
      
    - name: Move JAR and Dockerfile to workspace
      run: |
          mkdir -p $GITHUB_WORKSPACE/workspace
          mv target/gameService-0.0.1-SNAPSHOT.jar $GITHUB_WORKSPACE/workspace/gameService-0.0.1-SNAPSHOT.jar
          rm -rf src target pom.xml
      
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
       SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
       REMOTE_HOST: ${{ secrets.HOST }}
       REMOTE_USER: ${{ secrets.USERNAME }}
       TARGET: ${{ secrets.TARGET_DIR }}
      with:
       args: --no-group 

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /webapp 
            docker rmi gamedemo
            docker build -t gamedemo .
            docker run -d -p 8000:8080 gamedemo
    
